import type { FoodDishCatalogEntry } from "./types";

export const foodDishCatalog: readonly FoodDishCatalogEntry[] = [
  {
    id: "ramen",
    name: "Ramen",
    query: "ramen",
    aliases: ["shoyu ramen", "miso ramen"],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 100,
  },
  {
    id: "sushi",
    name: "Sushi",
    query: "sushi",
    aliases: ["maki", "nigiri"],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 98,
  },
  {
    id: "gyoza",
    name: "Gyoza",
    query: "gyoza",
    aliases: ["japanese dumplings"],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 92,
  },
  {
    id: "katsu",
    name: "Katsu",
    query: "katsu",
    aliases: ["tonkatsu", "chicken katsu"],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 88,
  },
  {
    id: "yakitori",
    name: "Yakitori",
    query: "yakitori",
    aliases: [],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 74,
  },
  {
    id: "udon",
    name: "Udon",
    query: "udon",
    aliases: [],
    cuisine: "Asiatisk",
    region: "Japan",
    explorerPriority: 72,
  },
  {
    id: "bao",
    name: "Bao",
    query: "bao",
    aliases: ["baozi"],
    cuisine: "Asiatisk",
    region: "Kina",
    explorerPriority: 92,
  },
  {
    id: "dumplings",
    name: "Dumplings",
    query: "dumplings",
    aliases: ["jiaozi"],
    cuisine: "Asiatisk",
    region: "Kina",
    explorerPriority: 90,
  },
  {
    id: "mapo-tofu",
    name: "Mapo tofu",
    query: "mapo tofu",
    aliases: [],
    cuisine: "Asiatisk",
    region: "Kina",
    explorerPriority: 82,
  },
  {
    id: "peking-duck",
    name: "Pekingand",
    query: "peking duck",
    aliases: ["pekingand"],
    cuisine: "Asiatisk",
    region: "Kina",
    explorerPriority: 76,
  },
  {
    id: "dan-dan-noodles",
    name: "Dan dan-nudler",
    query: "dan dan noodles",
    aliases: ["dandan"],
    cuisine: "Asiatisk",
    region: "Kina",
    explorerPriority: 70,
  },
  {
    id: "pad-thai",
    name: "Pad thai",
    query: "pad thai",
    aliases: [],
    cuisine: "Asiatisk",
    region: "Thailand",
    explorerPriority: 100,
  },
  {
    id: "green-curry",
    name: "Grønn curry",
    query: "green curry",
    aliases: ["thai green curry"],
    cuisine: "Asiatisk",
    region: "Thailand",
    explorerPriority: 92,
  },
  {
    id: "tom-yum",
    name: "Tom yum",
    query: "tom yum",
    aliases: [],
    cuisine: "Asiatisk",
    region: "Thailand",
    explorerPriority: 88,
  },
  {
    id: "pad-kra-pao",
    name: "Pad kra pao",
    query: "pad kra pao",
    aliases: ["pad krapow"],
    cuisine: "Asiatisk",
    region: "Thailand",
    explorerPriority: 84,
  },
  {
    id: "pho",
    name: "Phở",
    query: "pho",
    aliases: ["phở"],
    cuisine: "Asiatisk",
    region: "Vietnam",
    explorerPriority: 100,
  },
  {
    id: "banh-mi",
    name: "Bánh mì",
    query: "banh mi",
    aliases: ["bánh mì"],
    cuisine: "Asiatisk",
    region: "Vietnam",
    explorerPriority: 92,
  },
  {
    id: "bun-cha",
    name: "Bún chả",
    query: "bun cha",
    aliases: ["bún chả"],
    cuisine: "Asiatisk",
    region: "Vietnam",
    explorerPriority: 80,
  },
  {
    id: "vietnamese-spring-rolls",
    name: "Vietnamesiske vårruller",
    query: "vietnamese spring rolls",
    aliases: ["goi cuon", "gỏi cuốn"],
    cuisine: "Asiatisk",
    region: "Vietnam",
    explorerPriority: 78,
  },
  {
    id: "butter-chicken",
    name: "Butter chicken",
    query: "butter chicken",
    aliases: ["murgh makhani"],
    cuisine: "Indisk",
    region: "Nord-India",
    explorerPriority: 100,
  },
  {
    id: "tandoori",
    name: "Tandoori",
    query: "tandoori",
    aliases: ["tandoori chicken"],
    cuisine: "Indisk",
    region: "Nord-India",
    explorerPriority: 90,
  },
  {
    id: "chana-masala",
    name: "Chana masala",
    query: "chana masala",
    aliases: [],
    cuisine: "Indisk",
    region: "Nord-India",
    explorerPriority: 84,
  },
  {
    id: "naan",
    name: "Naan",
    query: "naan",
    aliases: [],
    cuisine: "Indisk",
    region: "Nord-India",
    explorerPriority: 82,
  },
  {
    id: "dal-makhani",
    name: "Dal makhani",
    query: "dal makhani",
    aliases: [],
    cuisine: "Indisk",
    region: "Nord-India",
    explorerPriority: 76,
  },
  {
    id: "dosa",
    name: "Dosa",
    query: "dosa",
    aliases: [],
    cuisine: "Indisk",
    region: "Sør-India",
    explorerPriority: 96,
  },
  {
    id: "idli",
    name: "Idli",
    query: "idli",
    aliases: [],
    cuisine: "Indisk",
    region: "Sør-India",
    explorerPriority: 74,
  },
  {
    id: "sambar",
    name: "Sambar",
    query: "sambar",
    aliases: [],
    cuisine: "Indisk",
    region: "Sør-India",
    explorerPriority: 72,
  },
  {
    id: "vada",
    name: "Vada",
    query: "vada",
    aliases: [],
    cuisine: "Indisk",
    region: "Sør-India",
    explorerPriority: 68,
  },
  {
    id: "biryani",
    name: "Biryani",
    query: "biryani",
    aliases: ["hyderabadi biryani"],
    cuisine: "Indisk",
    region: "Hyderabad",
    explorerPriority: 100,
  },
  {
    id: "haleem",
    name: "Haleem",
    query: "haleem",
    aliases: [],
    cuisine: "Indisk",
    region: "Hyderabad",
    explorerPriority: 72,
  },
  {
    id: "kebab-india",
    name: "Kebab",
    query: "kebab",
    aliases: [],
    cuisine: "Indisk",
    region: "Hyderabad",
    explorerPriority: 70,
  },
  {
    id: "mirchi-ka-salan",
    name: "Mirchi ka salan",
    query: "mirchi ka salan",
    aliases: [],
    cuisine: "Indisk",
    region: "Hyderabad",
    explorerPriority: 60,
  },
  {
    id: "cheeseburger",
    name: "Cheeseburger",
    query: "cheeseburger",
    aliases: [],
    cuisine: "Fast food",
    region: "Burger",
    explorerPriority: 100,
  },
  {
    id: "smashburger",
    name: "Smashburger",
    query: "smashburger",
    aliases: ["smash burger"],
    cuisine: "Fast food",
    region: "Burger",
    explorerPriority: 98,
  },
  {
    id: "chicken-burger",
    name: "Kyllingburger",
    query: "chicken burger",
    aliases: [],
    cuisine: "Fast food",
    region: "Burger",
    explorerPriority: 86,
  },
  {
    id: "veggie-burger",
    name: "Vegetarburger",
    query: "veggie burger",
    aliases: ["vegetarburger"],
    cuisine: "Fast food",
    region: "Burger",
    explorerPriority: 72,
  },
  {
    id: "fried-chicken",
    name: "Fried chicken",
    query: "fried chicken",
    aliases: [],
    cuisine: "Fast food",
    region: "Fried chicken",
    explorerPriority: 100,
  },
  {
    id: "chicken-wings",
    name: "Chicken wings",
    query: "chicken wings",
    aliases: ["wings"],
    cuisine: "Fast food",
    region: "Fried chicken",
    explorerPriority: 90,
  },
  {
    id: "chicken-tenders",
    name: "Chicken tenders",
    query: "chicken tenders",
    aliases: [],
    cuisine: "Fast food",
    region: "Fried chicken",
    explorerPriority: 78,
  },
  {
    id: "hot-chicken",
    name: "Hot chicken",
    query: "hot chicken",
    aliases: [],
    cuisine: "Fast food",
    region: "Fried chicken",
    explorerPriority: 70,
  },
  {
    id: "hot-dog",
    name: "Hot dog",
    query: "hot dog",
    aliases: ["pølse"],
    cuisine: "Fast food",
    region: "Hot dog",
    explorerPriority: 100,
  },
  {
    id: "chili-dog",
    name: "Chili dog",
    query: "chili dog",
    aliases: [],
    cuisine: "Fast food",
    region: "Hot dog",
    explorerPriority: 65,
  },
  {
    id: "corn-dog",
    name: "Corn dog",
    query: "corn dog",
    aliases: [],
    cuisine: "Fast food",
    region: "Hot dog",
    explorerPriority: 60,
  },
  {
    id: "carbonara",
    name: "Carbonara",
    query: "carbonara",
    aliases: ["pasta carbonara"],
    cuisine: "Italiensk",
    region: "Roma",
    explorerPriority: 100,
  },
  {
    id: "cacio-e-pepe",
    name: "Cacio e pepe",
    query: "cacio e pepe",
    aliases: [],
    cuisine: "Italiensk",
    region: "Roma",
    explorerPriority: 94,
  },
  {
    id: "amatriciana",
    name: "Amatriciana",
    query: "amatriciana",
    aliases: ["pasta amatriciana"],
    cuisine: "Italiensk",
    region: "Roma",
    explorerPriority: 88,
  },
  {
    id: "saltimbocca",
    name: "Saltimbocca",
    query: "saltimbocca",
    aliases: [],
    cuisine: "Italiensk",
    region: "Roma",
    explorerPriority: 74,
  },
  {
    id: "pizza-margherita",
    name: "Pizza margherita",
    query: "pizza margherita",
    aliases: ["margherita"],
    cuisine: "Italiensk",
    region: "Napoli",
    explorerPriority: 100,
  },
  {
    id: "pizza-marinara",
    name: "Pizza marinara",
    query: "pizza marinara",
    aliases: ["marinara pizza"],
    cuisine: "Italiensk",
    region: "Napoli",
    explorerPriority: 76,
  },
  {
    id: "frittatina",
    name: "Frittatina",
    query: "frittatina",
    aliases: [],
    cuisine: "Italiensk",
    region: "Napoli",
    explorerPriority: 60,
  },
  {
    id: "sfogliatella",
    name: "Sfogliatella",
    query: "sfogliatella",
    aliases: [],
    cuisine: "Italiensk",
    region: "Napoli",
    explorerPriority: 56,
  },
  {
    id: "arancini",
    name: "Arancini",
    query: "arancini",
    aliases: ["arancine"],
    cuisine: "Italiensk",
    region: "Sicilia",
    explorerPriority: 90,
  },
  {
    id: "pasta-alla-norma",
    name: "Pasta alla Norma",
    query: "pasta alla norma",
    aliases: [],
    cuisine: "Italiensk",
    region: "Sicilia",
    explorerPriority: 82,
  },
  {
    id: "caponata",
    name: "Caponata",
    query: "caponata",
    aliases: [],
    cuisine: "Italiensk",
    region: "Sicilia",
    explorerPriority: 68,
  },
  {
    id: "cannoli",
    name: "Cannoli",
    query: "cannoli",
    aliases: [],
    cuisine: "Italiensk",
    region: "Sicilia",
    explorerPriority: 72,
  },
  {
    id: "falafel",
    name: "Falafel",
    query: "falafel",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Levanten",
    explorerPriority: 100,
  },
  {
    id: "shawarma",
    name: "Shawarma",
    query: "shawarma",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Levanten",
    explorerPriority: 98,
  },
  {
    id: "hummus",
    name: "Hummus",
    query: "hummus",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Levanten",
    explorerPriority: 94,
  },
  {
    id: "manakish",
    name: "Manakish",
    query: "manakish",
    aliases: ["manoushe"],
    cuisine: "Midtøsten",
    region: "Levanten",
    explorerPriority: 78,
  },
  {
    id: "fattoush",
    name: "Fattoush",
    query: "fattoush",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Levanten",
    explorerPriority: 65,
  },
  {
    id: "taameya",
    name: "Ta'ameya",
    query: "taameya",
    aliases: ["ta'ameya"],
    cuisine: "Midtøsten",
    region: "Egypt",
    explorerPriority: 78,
  },
  {
    id: "koshari",
    name: "Koshari",
    query: "koshari",
    aliases: ["koshary"],
    cuisine: "Midtøsten",
    region: "Egypt",
    explorerPriority: 88,
  },
  {
    id: "ful-medames",
    name: "Ful medames",
    query: "ful medames",
    aliases: ["ful"],
    cuisine: "Midtøsten",
    region: "Egypt",
    explorerPriority: 72,
  },
  {
    id: "fattah",
    name: "Fattah",
    query: "fattah",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Egypt",
    explorerPriority: 60,
  },
  {
    id: "doner",
    name: "Döner",
    query: "doner",
    aliases: ["döner"],
    cuisine: "Midtøsten",
    region: "Tyrkia",
    explorerPriority: 100,
  },
  {
    id: "pide",
    name: "Pide",
    query: "pide",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Tyrkia",
    explorerPriority: 90,
  },
  {
    id: "lahmacun",
    name: "Lahmacun",
    query: "lahmacun",
    aliases: [],
    cuisine: "Midtøsten",
    region: "Tyrkia",
    explorerPriority: 84,
  },
  {
    id: "manti",
    name: "Mantı",
    query: "manti",
    aliases: ["mantı"],
    cuisine: "Midtøsten",
    region: "Tyrkia",
    explorerPriority: 70,
  },
  {
    id: "tacos-al-pastor",
    name: "Tacos al pastor",
    query: "tacos al pastor",
    aliases: ["al pastor"],
    cuisine: "Mexicansk",
    region: "Sentral-Mexico",
    explorerPriority: 100,
  },
  {
    id: "quesadilla",
    name: "Quesadilla",
    query: "quesadilla",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Sentral-Mexico",
    explorerPriority: 92,
  },
  {
    id: "pozole",
    name: "Pozole",
    query: "pozole",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Sentral-Mexico",
    explorerPriority: 78,
  },
  {
    id: "tlacoyo",
    name: "Tlacoyo",
    query: "tlacoyo",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Sentral-Mexico",
    explorerPriority: 58,
  },
  {
    id: "birria",
    name: "Birria",
    query: "birria",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Jalisco",
    explorerPriority: 100,
  },
  {
    id: "torta-ahogada",
    name: "Torta ahogada",
    query: "torta ahogada",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Jalisco",
    explorerPriority: 66,
  },
  {
    id: "carne-en-su-jugo",
    name: "Carne en su jugo",
    query: "carne en su jugo",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Jalisco",
    explorerPriority: 58,
  },
  {
    id: "pozole-rojo",
    name: "Pozole rojo",
    query: "pozole rojo",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Jalisco",
    explorerPriority: 60,
  },
  {
    id: "cochinita-pibil",
    name: "Cochinita pibil",
    query: "cochinita pibil",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Yucatán",
    explorerPriority: 96,
  },
  {
    id: "sopa-de-lima",
    name: "Sopa de lima",
    query: "sopa de lima",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Yucatán",
    explorerPriority: 62,
  },
  {
    id: "panuchos",
    name: "Panuchos",
    query: "panuchos",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Yucatán",
    explorerPriority: 58,
  },
  {
    id: "papadzules",
    name: "Papadzules",
    query: "papadzules",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Yucatán",
    explorerPriority: 52,
  },
  {
    id: "fish-taco",
    name: "Fish taco",
    query: "fish taco",
    aliases: ["fish tacos"],
    cuisine: "Mexicansk",
    region: "Baja",
    explorerPriority: 100,
  },
  {
    id: "shrimp-taco",
    name: "Shrimp taco",
    query: "shrimp taco",
    aliases: ["shrimp tacos"],
    cuisine: "Mexicansk",
    region: "Baja",
    explorerPriority: 90,
  },
  {
    id: "ceviche",
    name: "Ceviche",
    query: "ceviche",
    aliases: [],
    cuisine: "Mexicansk",
    region: "Baja",
    explorerPriority: 84,
  },
  {
    id: "tostada",
    name: "Tostada",
    query: "tostada",
    aliases: ["tostadas"],
    cuisine: "Mexicansk",
    region: "Baja",
    explorerPriority: 72,
  },
];

const catalogById = new Map(foodDishCatalog.map((dish) => [dish.id, dish]));

export function getFoodDish(id: string): FoodDishCatalogEntry {
  const dish = catalogById.get(id);
  if (!dish) throw new Error(`Unknown canonical food dish: ${id}`);
  return dish;
}

export function findFoodDishByQuery(value: string): FoodDishCatalogEntry | null {
  const normalized = value.trim().toLocaleLowerCase("nb-NO").replace(/\s+/g, " ");
  if (!normalized) return null;
  return foodDishCatalog.find((dish) =>
    [dish.name, dish.query, ...dish.aliases].some(
      (candidate) => candidate.toLocaleLowerCase("nb-NO").replace(/\s+/g, " ") === normalized,
    ),
  ) ?? null;
}
