import { foodDishCatalog } from "./catalog";
import type { FoodDishCatalogEntry } from "./types";

const productionBackedMatlystDishes: readonly FoodDishCatalogEntry[] = [
  {
    id: "bibimbap",
    name: "Bibimbap",
    query: "bibimbap",
    aliases: ["bibimbap vegan"],
    cuisine: "Koreansk",
    region: "Korea",
    explorerPriority: 100,
  },
  {
    id: "bulgogi",
    name: "Bulgogi",
    query: "bulgogi",
    aliases: ["beef bulgogi bowl", "spicy pork bulgogi bowl"],
    cuisine: "Koreansk",
    region: "Korea",
    explorerPriority: 96,
  },
  {
    id: "tteokbokki",
    name: "Tteokbokki",
    query: "tteokbokki",
    aliases: [],
    cuisine: "Koreansk",
    region: "Korea",
    explorerPriority: 94,
  },
  {
    id: "mandu",
    name: "Mandu",
    query: "mandu",
    aliases: ["deep-fried mandu", "deep fried mandu"],
    cuisine: "Koreansk",
    region: "Korea",
    explorerPriority: 86,
  },
  {
    id: "sisig",
    name: "Sisig",
    query: "sisig",
    aliases: [],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 100,
  },
  {
    id: "pork-adobo",
    name: "Pork adobo",
    query: "pork adobo",
    aliases: ["adobo"],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 98,
  },
  {
    id: "chicken-inasal",
    name: "Chicken inasal",
    query: "chicken inasal",
    aliases: ["inasal"],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 96,
  },
  {
    id: "kare-kare",
    name: "Kare-kare",
    query: "kare-kare",
    aliases: ["vegan kare-kare", "kare kare"],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 88,
  },
  {
    id: "sinuglaw",
    name: "Sinuglaw",
    query: "sinuglaw",
    aliases: [],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 84,
  },
  {
    id: "siomai",
    name: "Siomai",
    query: "siomai",
    aliases: [],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 82,
  },
  {
    id: "pinakbet",
    name: "Pinakbet",
    query: "pinakbet",
    aliases: [],
    cuisine: "Filippinsk",
    region: "Filippinene",
    explorerPriority: 78,
  },
  {
    id: "pao-de-queijo",
    name: "Pão de queijo",
    query: "pao de queijo",
    aliases: ["pão de queijo"],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 100,
  },
  {
    id: "coxinha",
    name: "Coxinha",
    query: "coxinha",
    aliases: [],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 98,
  },
  {
    id: "bolinhos-de-bacalhau",
    name: "Bolinhos de bacalhau",
    query: "bolinhos de bacalhau",
    aliases: ["bolinho de bacalhau"],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 92,
  },
  {
    id: "mandioca-frita",
    name: "Mandioca frita",
    query: "mandioca frita",
    aliases: [],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 88,
  },
  {
    id: "frango-a-passarinho",
    name: "Frango a passarinho",
    query: "frango a passarinho",
    aliases: [],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 86,
  },
  {
    id: "camarao-alho-oleo",
    name: "Camarão ao alho e óleo",
    query: "camarao ao alho e oleo",
    aliases: ["camarão ao alho e óleo"],
    cuisine: "Brasiliansk",
    region: "Brasil",
    explorerPriority: 82,
  },
  {
    id: "momo",
    name: "Momo",
    query: "momo",
    aliases: ["mo mo", "chicken mo mo", "green mo mo", "chicken mo mo dumplings"],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 100,
  },
  {
    id: "jhol-momo",
    name: "Jhol momo",
    query: "jhol momo",
    aliases: ["jhol mo mo", "chicken jhol mo mo", "green jhol mo mo"],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 96,
  },
  {
    id: "nepali-chowmein",
    name: "Chowmein",
    query: "chowmein",
    aliases: ["chicken chowmein", "veg chowmein"],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 88,
  },
  {
    id: "sekuwa",
    name: "Sekuwa",
    query: "sekuwa",
    aliases: ["pork sekuwa"],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 86,
  },
  {
    id: "choila",
    name: "Choila",
    query: "choila",
    aliases: ["choila chicken"],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 82,
  },
  {
    id: "jhaneko-dal",
    name: "Jhaneko dal",
    query: "jhaneko dal",
    aliases: [],
    cuisine: "Nepalsk",
    region: "Nepal",
    explorerPriority: 78,
  },
  {
    id: "chicken-tikka-masala-pakistan",
    name: "Kylling tikka masala",
    query: "kylling tikka masala",
    aliases: ["chicken tikka masala"],
    cuisine: "Pakistansk",
    region: "Lahore",
    explorerPriority: 100,
  },
  {
    id: "lahori-karahi",
    name: "Lahori karahi",
    query: "lahori karahi",
    aliases: ["lahori lam karahi fresh", "karahi"],
    cuisine: "Pakistansk",
    region: "Lahore",
    explorerPriority: 98,
  },
  {
    id: "chapli-kebab",
    name: "Chapli kebab",
    query: "chapli kebab",
    aliases: [],
    cuisine: "Pakistansk",
    region: "Lahore",
    explorerPriority: 94,
  },
  {
    id: "saag-paneer",
    name: "Saag paneer",
    query: "saag paneer",
    aliases: [],
    cuisine: "Pakistansk",
    region: "Lahore",
    explorerPriority: 86,
  },
  {
    id: "pakistani-mix-grill",
    name: "Mix grill",
    query: "mix grill",
    aliases: ["mixed grill"],
    cuisine: "Pakistansk",
    region: "Lahore",
    explorerPriority: 82,
  },
  {
    id: "koobideh",
    name: "Koobideh",
    query: "koobideh",
    aliases: [],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 100,
  },
  {
    id: "ghormeh-sabzi",
    name: "Ghormeh sabzi",
    query: "ghormeh sabzi",
    aliases: [],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 98,
  },
  {
    id: "zereshk-polo",
    name: "Zereshk polo",
    query: "zereshk polo",
    aliases: ["zereshk polo ba morgh"],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 94,
  },
  {
    id: "kashke-bademjan",
    name: "Kashke bademjan",
    query: "kashke bademjan",
    aliases: [],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 90,
  },
  {
    id: "mirza-ghasemi",
    name: "Mirza ghasemi",
    query: "mirza ghasemi",
    aliases: [],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 86,
  },
  {
    id: "joojeh",
    name: "Joojeh",
    query: "joojeh",
    aliases: [],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 82,
  },
  {
    id: "baghali-polo",
    name: "Baghali polo",
    query: "baghali polo",
    aliases: ["baghali polo ba mahiche", "baghali polo ba gardan", "baghali polo ba mahiche gardan"],
    cuisine: "Persisk",
    region: "Iran",
    explorerPriority: 78,
  },
  {
    id: "uzbek-plov",
    name: "Usbekisk plov",
    query: "usbekisk plov",
    aliases: ["plov", "vegetar usbekisk plov"],
    cuisine: "Usbekisk",
    region: "Usbekistan",
    explorerPriority: 100,
  },
  {
    id: "lagman",
    name: "Lagman",
    query: "lagman",
    aliases: ["stekt lagman"],
    cuisine: "Usbekisk",
    region: "Usbekistan",
    explorerPriority: 96,
  },
  {
    id: "qazon-kebab",
    name: "Qazon kebab",
    query: "qazon kebab",
    aliases: ["usbekisk qazon kebab", "oksehale qazon kebab", "kylling qazon kebab"],
    cuisine: "Usbekisk",
    region: "Usbekistan",
    explorerPriority: 92,
  },
  {
    id: "manty",
    name: "Manty",
    query: "manty",
    aliases: ["stekt manty"],
    cuisine: "Usbekisk",
    region: "Usbekistan",
    explorerPriority: 88,
  },
  {
    id: "uzbek-samosa",
    name: "Samosa",
    query: "samosa",
    aliases: ["biff samosa"],
    cuisine: "Usbekisk",
    region: "Usbekistan",
    explorerPriority: 80,
  },
  {
    id: "pierogi",
    name: "Pierogi",
    query: "pierogi",
    aliases: ["pierogi z miesem", "pierogi z mięsem okraszone skwarkami"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 100,
  },
  {
    id: "bigos",
    name: "Bigos",
    query: "bigos",
    aliases: ["bigos pieczywo"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 96,
  },
  {
    id: "kotlet-schabowy",
    name: "Kotlet schabowy",
    query: "kotlet schabowy",
    aliases: ["kotlet schabowy panierowany"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 92,
  },
  {
    id: "zurek",
    name: "Żur",
    query: "zur",
    aliases: ["żur", "żur z jajkiem i kiełbasą"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 88,
  },
  {
    id: "nalesniki",
    name: "Naleśniki",
    query: "nalesniki",
    aliases: ["naleśniki", "nalesniki z serem"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 84,
  },
  {
    id: "kielbasa",
    name: "Kiełbasa",
    query: "kielbasa",
    aliases: ["kiełbasa", "kiełbasa z grilla z cebulką pieczywo"],
    cuisine: "Polsk",
    region: "Polen",
    explorerPriority: 80,
  },
];

const existingIds = new Set(foodDishCatalog.map((dish) => dish.id));
for (const dish of productionBackedMatlystDishes) {
  if (existingIds.has(dish.id)) {
    throw new Error(`Duplicate canonical discovery dish id: ${dish.id}`);
  }
  existingIds.add(dish.id);
}

export const foodDiscoveryCatalog: readonly FoodDishCatalogEntry[] = [
  ...foodDishCatalog,
  ...productionBackedMatlystDishes,
];
